name = "BracketCityPuzzle"
uuid = "03fc92bf-40bd-4d52-853f-4fa1c8d30825"
version = "1.0.0-DEV"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]

[deps]
Cascadia = "54eefc05-d75b-58de-a785-1a3403f0919f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
WebScrapingTools = "8afffa6a-3076-4974-917d-2ce0a0fc8257"

[sources]
WebScrapingTools = {url = "https://github.com/MarkNahabedian/WebScrapingTools.jl"}

[compat]
Cascadia = "1.0.2"
DataStructures = "0.19.1"
Dates = "1.11.0"
Gumbo = "0.8.3"
WebScrapingTools = "1.0.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
